"use client";

import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import Link from "next/link";
import { ArrowRight, Bot, Target, Mail, Calendar, BarChart3, Zap, CheckCircle, Layers, Shield } from "lucide-react";
import { SplineScene } from "@/components/ui/spline-scene";
import { Card } from "@/components/ui/card";
import { Spotlight } from "@/components/ui/aceternity-spotlight";

// ─── Fade-up animation preset ──────────────────────────────────────────────
const fadeUp = {
  hidden: { opacity: 0, y: 18 },
  visible: (delay = 0) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, delay, ease: [0.22, 1, 0.36, 1] },
  }),
};

function FadeSection({ children, delay = 0, className = "" }) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });
  return (
    <motion.div
      ref={ref}
      initial="hidden"
      animate={inView ? "visible" : "hidden"}
      custom={delay}
      variants={fadeUp}
      className={className}
    >
      {children}
    </motion.div>
  );
}

// ─── Features ────────────────────────────────────────────────────────────
const features = [
  {
    icon: <Target className="w-5 h-5 text-[#62D2A2]" />,
    title: "Lead Mapping & Enrichment",
    description: "The agent auto-identifies and enriches leads that match your ICP — surfacing the data your reps need before the first touchpoint.",
  },
  {
    icon: <Mail className="w-5 h-5 text-[#62D2A2]" />,
    title: "Automated Outreach",
    description: "Personalized sequences drafted and queued automatically. Reps review and approve — zero manual copy-paste, zero template hunting.",
  },
  {
    icon: <Calendar className="w-5 h-5 text-[#62D2A2]" />,
    title: "Meeting Management",
    description: "Pre-call briefs, agenda prep, follow-up summaries — all generated by the agent and pushed to your CRM before and after every meeting.",
  },
  {
    icon: <BarChart3 className="w-5 h-5 text-[#62D2A2]" />,
    title: "Deal Analysis & Next Steps",
    description: "The agent analyzes deal health, flags risk signals, and proposes concrete next steps — so reps always know what to do with a stalled deal.",
  },
  {
    icon: <Zap className="w-5 h-5 text-[#62D2A2]" />,
    title: "Live Deal Support",
    description: "Real-time context served during active deals. Competitive positioning, objection responses, pricing context — right inside the workflow.",
  },
];

// ─── Stages ──────────────────────────────────────────────────────────────
const stages = ["Prospecting", "Outreach", "Meetings", "Deal Execution"];

// ─── Integrations ────────────────────────────────────────────────────────
const integrations = [
  { name: "HubSpot", color: "#ff7a59" },
  { name: "Salesforce", color: "#00a1e0" },
  { name: "Pipedrive", color: "#1a73e8" },
  { name: "Gmail", color: "#ea4335" },
  { name: "Slack", color: "#4a154b" },
];

export default function AISalesAssistantPage() {
  return (
    <div className="bg-[#050505] text-white min-h-screen overflow-x-hidden">

      <section className="relative w-full h-[100vh] min-h-[900px] flex items-center overflow-hidden bg-black">
        {/* Aceternity spotlight beam — sweeps in from top-left */}
        <Spotlight
          className="-top-40 left-0 md:left-60 md:-top-20"
          fill="#62D2A2"
        />

        {/* ── Interactive Spline 3D scene (Placed behind content but fully interactive) ──────────────── */}
        <div className="absolute top-0 right-0 w-full md:w-[70%] lg:w-[75%] h-full z-10 select-none">
          <div className="w-full h-full transform scale-110 lg:scale-135 origin-center translate-x-[15%] md:translate-x-[20%]">
            <SplineScene
              scene="https://prod.spline.design/kZDDjO5HuC9GJUM2/scene.splinecode"
              className="w-full h-full"
            />
          </div>
        </div>

        {/* ── Foreground Content ──────────────── */}
        <div className="container mx-auto px-6 md:px-12 relative z-20 w-full h-full flex items-center pointer-events-none">
          <div className="max-w-4xl pointer-events-auto">
            <div className="flex flex-col justify-center">
              <FadeSection delay={0}>
                <div className="flex items-center gap-3 mb-8">
                  <div className="w-10 h-[1px] bg-[#62D2A2]/40" />
                  <span className="text-[11px] font-black tracking-[0.4em] text-[#62D2A2] uppercase">
                    AI Sales Assistant
                  </span>
                </div>
              </FadeSection>

              <FadeSection delay={0.08}>
                <h1 className="text-6xl md:text-7xl lg:text-8xl font-black tracking-tighter leading-[0.92] mb-10 bg-clip-text text-transparent bg-gradient-to-b from-neutral-50 to-neutral-400">
                  Your Sales Motion Just Got an{" "}
                  <span className="text-[#62D2A2] bg-none" style={{WebkitTextFillColor:"#62D2A2"}}>
                    Unfair Advantage
                  </span>.
                </h1>
              </FadeSection>

              <FadeSection delay={0.14}>
                <p className="text-xl text-neutral-400 leading-relaxed mb-12 max-w-lg font-medium">
                  An AI-powered agent working inside your CRM across every stage of the deal — from first touch to closed-won.
                </p>
              </FadeSection>

              <FadeSection delay={0.2}>
                <div className="flex flex-col sm:flex-row items-start sm:items-center gap-6">
                  <Link
                    href="#waitlist"
                    className="group inline-flex items-center gap-3 bg-[#62D2A2] text-black px-10 py-5 font-black text-sm uppercase tracking-widest rounded-full hover:bg-white hover:scale-105 transition-all duration-300"
                  >
                    Join the Waitlist
                    <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                  </Link>
                  <Link
                    href="#what-it-does"
                    className="text-neutral-500 hover:text-white transition-colors text-sm font-black uppercase tracking-widest flex items-center gap-3 group"
                  >
                    See capabilities
                    <span className="group-hover:translate-x-1 transition-transform">→</span>
                  </Link>
                </div>
              </FadeSection>

              {/* Floating stat pill */}
              <FadeSection delay={0.3} className="mt-20">
                <div className="inline-flex items-center gap-4 px-5 py-4 rounded-2xl border border-white/5 bg-white/[0.02] backdrop-blur-sm">
                  <div className="relative">
                    <div className="w-2 h-2 rounded-full bg-[#62D2A2] animate-ping absolute inset-0" />
                    <div className="w-2 h-2 rounded-full bg-[#62D2A2] relative" />
                  </div>
                  <span className="text-[11px] font-black text-white/40 uppercase tracking-[0.2em]">Human-in-the-loop</span>
                  <div className="w-px h-3 bg-white/10" />
                  <span className="text-[11px] font-bold text-white/30 tracking-wide uppercase">AI suggests. You decide.</span>
                </div>
              </FadeSection>
            </div>
          </div>
        </div>
      </section>

      {/* ── Section gap ─────────────────────────────────────────────── */}
      <div className="h-28" />

      {/* Divider */}
      <div className="max-w-[1400px] mx-auto px-6 md:px-16">
        <div className="h-px bg-white/5" />
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          SECTION 2 — OVERVIEW / STAGES
      ────────────────────────────────────────────────────────────────── */}
      <section className="py-28 px-6 md:px-16 max-w-[1400px] mx-auto">
        <FadeSection delay={0} className="mb-16">
          <span className="inline-block text-[11px] font-black tracking-[0.3em] text-white/25 uppercase mb-6">
            Full-Funnel Coverage
          </span>
          <h2 className="text-4xl md:text-5xl font-black tracking-tight leading-[1.05] max-w-2xl">
            One agent. Every stage.
          </h2>
        </FadeSection>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {stages.map((stage, i) => (
            <FadeSection key={stage} delay={0.06 * i}>
              <div className="group flex flex-col gap-4 p-6 border border-white/6 rounded-2xl bg-white/[0.02] hover:border-[#62D2A2]/20 hover:bg-white/[0.04] transition-all duration-300">
                <span className="text-[10px] font-black tracking-[0.2em] text-white/20 uppercase">
                  Stage {i + 1}
                </span>
                <p className="text-lg font-black text-white">{stage}</p>
                <div className="w-6 h-0.5 bg-[#62D2A2]/30 group-hover:w-10 group-hover:bg-[#62D2A2] transition-all duration-300" />
              </div>
            </FadeSection>
          ))}
        </div>

        <FadeSection delay={0.3} className="mt-12">
          <p className="text-gray-500 text-base leading-relaxed max-w-2xl">
            Most AI tools solve one problem in one stage. Our agent operates across your entire deal lifecycle — from first touch to closed-won — with full context of every interaction.
          </p>
        </FadeSection>
      </section>

      {/* Divider */}
      <div className="max-w-[1400px] mx-auto px-6 md:px-16">
        <div className="h-px bg-white/5" />
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          SECTION 3 — WHAT IT DOES
      ────────────────────────────────────────────────────────────────── */}
      <section id="what-it-does" className="py-28 px-6 md:px-16 max-w-[1400px] mx-auto">
        <FadeSection delay={0} className="mb-16">
          <span className="inline-block text-[11px] font-black tracking-[0.3em] text-white/25 uppercase mb-6">
            Capabilities
          </span>
          <h2 className="text-4xl md:text-5xl font-black tracking-tight leading-[1.05]">
            What the agent does.
          </h2>
        </FadeSection>

        <div className="flex flex-col divide-y divide-white/5">
          {features.map((feature, i) => (
            <FadeSection key={feature.title} delay={0.06 * i}>
              <div className="group grid md:grid-cols-[1fr_2fr] gap-8 md:gap-16 py-10 hover:bg-white/[0.015] px-4 -mx-4 rounded-xl transition-all duration-300">
                <div className="flex items-start gap-4">
                  <div className="mt-0.5 w-8 h-8 rounded-lg bg-[#62D2A2]/8 border border-[#62D2A2]/15 flex items-center justify-center shrink-0">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-black text-white leading-tight">{feature.title}</h3>
                </div>
                <p className="text-gray-400 leading-relaxed self-center">{feature.description}</p>
              </div>
            </FadeSection>
          ))}
        </div>
      </section>

      {/* Divider */}
      <div className="max-w-[1400px] mx-auto px-6 md:px-16">
        <div className="h-px bg-white/5" />
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          SECTION 4 — PRODUCT EXPERIENCE
      ────────────────────────────────────────────────────────────────── */}
      <section className="py-28 px-6 md:px-16 max-w-[1400px] mx-auto">
        <div className="grid md:grid-cols-2 gap-16 md:gap-24 items-center">
          {/* Left: Text */}
          <div>
            <FadeSection delay={0}>
              <span className="inline-block text-[11px] font-black tracking-[0.3em] text-white/25 uppercase mb-6">
                Product Experience
              </span>
              <h2 className="text-4xl md:text-5xl font-black tracking-tight leading-[1.05] mb-8">
                Works where{" "}
                <span className="text-[#62D2A2]">your reps</span>{" "}
                already work.
              </h2>
            </FadeSection>

            <FadeSection delay={0.08}>
              <p className="text-gray-400 text-lg leading-relaxed mb-10">
                No new software to learn. No replatforming. No rep adoption risk.
              </p>
            </FadeSection>

            <div className="flex flex-col gap-5">
              {[
                { icon: <Layers className="w-4 h-4" />, title: "Web App", desc: "Full dashboard for deal analysis, pipeline health, and agent activity." },
                { icon: <Shield className="w-4 h-4" />, title: "Browser Extension", desc: "AI context layer that overlays your CRM — no alt-tabbing, no copy-paste." },
                { icon: <Zap className="w-4 h-4" />, title: "Native CRM Integration", desc: "Syncs bidirectionally with your CRM in real time. Zero data loss." },
              ].map((item, i) => (
                <FadeSection key={item.title} delay={0.06 * i}>
                  <div className="flex items-start gap-4">
                    <div className="mt-0.5 w-8 h-8 rounded-lg bg-white/5 border border-white/8 flex items-center justify-center text-[#62D2A2] shrink-0">
                      {item.icon}
                    </div>
                    <div>
                      <p className="font-bold text-white mb-1">{item.title}</p>
                      <p className="text-gray-500 text-sm leading-relaxed">{item.desc}</p>
                    </div>
                  </div>
                </FadeSection>
              ))}
            </div>
          </div>

          {/* Right: Screenshot placeholder */}
          <FadeSection delay={0.1}>
            <div className="relative">
              <div className="border border-white/8 rounded-2xl bg-white/[0.02] aspect-[4/3] flex items-center justify-center overflow-hidden">
                {/* Simulated UI screenshot */}
                <div className="w-full h-full p-5 flex flex-col gap-3">
                  {/* Window bar */}
                  <div className="flex items-center gap-2 mb-2">
                    <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
                    <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
                    <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
                    <div className="flex-1 h-2.5 rounded bg-white/5 ml-4" />
                  </div>
                  {/* Fake sidebar + content */}
                  <div className="flex gap-3 flex-1">
                    <div className="w-24 flex flex-col gap-2">
                      {[80, 60, 90, 50, 70].map((w, j) => (
                        <div key={j} className="h-2 rounded bg-white/5" style={{width:`${w}%`}} />
                      ))}
                    </div>
                    <div className="flex-1 flex flex-col gap-3">
                      <div className="h-8 rounded-lg bg-[#62D2A2]/8 border border-[#62D2A2]/15" />
                      <div className="grid grid-cols-2 gap-2 flex-1">
                        {[1,2,3,4].map(k => (
                          <div key={k} className="rounded-lg bg-white/[0.03] border border-white/5 p-2 flex flex-col gap-1.5">
                            <div className="w-1/2 h-1.5 rounded bg-[#62D2A2]/20" />
                            <div className="w-3/4 h-1.5 rounded bg-white/10" />
                            <div className="w-2/3 h-1.5 rounded bg-white/5" />
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent pointer-events-none" />
                <div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-[10px] text-white/20 tracking-widest uppercase font-medium">
                  Product screenshots coming soon
                </div>
              </div>
            </div>
          </FadeSection>
        </div>
      </section>

      {/* Divider */}
      <div className="max-w-[1400px] mx-auto px-6 md:px-16">
        <div className="h-px bg-white/5" />
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          SECTION 5 — INTEGRATIONS
      ────────────────────────────────────────────────────────────────── */}
      <section className="py-28 px-6 md:px-16 max-w-[1400px] mx-auto">
        <FadeSection delay={0} className="text-center mb-16">
          <span className="inline-block text-[11px] font-black tracking-[0.3em] text-white/25 uppercase mb-6">
            Integrations
          </span>
          <h2 className="text-3xl md:text-4xl font-black tracking-tight">
            Works with your stack.
          </h2>
        </FadeSection>

        <FadeSection delay={0.1}>
          <div className="flex flex-wrap items-center justify-center gap-4">
            {integrations.map((integration) => (
              <div
                key={integration.name}
                className="group px-6 py-4 border border-white/8 rounded-xl bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.05] transition-all duration-300 cursor-default"
              >
                <div className="flex items-center justify-center gap-3">
                  {/* Colored dot as brand indicator */}
                  <div
                    className="w-2.5 h-2.5 rounded-full opacity-40 group-hover:opacity-100 transition-opacity"
                    style={{ backgroundColor: integration.color }}
                  />
                  <span className="text-sm font-bold text-white/40 group-hover:text-white transition-colors">
                    {integration.name}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </FadeSection>

        <FadeSection delay={0.2} className="text-center mt-10">
          <p className="text-gray-600 text-sm">More integrations available. Ask us about your stack.</p>
        </FadeSection>
      </section>

      {/* Divider */}
      <div className="max-w-[1400px] mx-auto px-6 md:px-16">
        <div className="h-px bg-white/5" />
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          SECTION 6 — HUMAN IN THE LOOP
      ────────────────────────────────────────────────────────────────── */}
      <section className="py-28 px-6 md:px-16 max-w-[1400px] mx-auto">
        <div className="max-w-3xl">
          <FadeSection delay={0}>
            <span className="inline-block text-[11px] font-black tracking-[0.3em] text-white/25 uppercase mb-8">
              Human in the Loop
            </span>
          </FadeSection>

          <FadeSection delay={0.08}>
            <h2 className="text-4xl md:text-6xl font-black tracking-tight leading-tight mb-10">
              AI suggests.{" "}
              <span className="text-[#62D2A2]">You decide.</span>
            </h2>
          </FadeSection>

          <FadeSection delay={0.14}>
            <p className="text-gray-400 text-lg leading-relaxed mb-12 max-w-xl">
              The agent never sends an email, books a meeting, or advances a deal without rep approval. It does the thinking. Your rep makes the call.
            </p>
          </FadeSection>

          <div className="grid md:grid-cols-2 gap-6">
            {[
              {
                from: "AI analyzes deal",
                to: "Rep gets action recommendation",
                detail: "Structured, specific, ready to act on.",
              },
              {
                from: "AI drafts outreach",
                to: "Rep reviews and approves",
                detail: "Personalized copy — rep just hits send.",
              },
            ].map((flow, i) => (
              <FadeSection key={flow.from} delay={0.06 * i}>
                <div className="p-6 border border-white/6 rounded-2xl bg-white/[0.02]">
                  <div className="flex items-center gap-3 mb-4">
                    <span className="text-sm text-white/30">{flow.from}</span>
                    <ArrowRight className="w-3.5 h-3.5 text-[#62D2A2]/40 shrink-0" />
                    <span className="text-sm font-bold text-white">{flow.to}</span>
                  </div>
                  <p className="text-gray-500 text-sm">{flow.detail}</p>
                </div>
              </FadeSection>
            ))}
          </div>
        </div>
      </section>

      {/* Divider */}
      <div className="max-w-[1400px] mx-auto px-6 md:px-16">
        <div className="h-px bg-white/5" />
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          SECTION 7 — CTA / WAITLIST
      ────────────────────────────────────────────────────────────────── */}
      <section id="waitlist" className="py-40 px-6 text-center">
        <div className="max-w-3xl mx-auto">
          <FadeSection delay={0}>
            <span className="inline-block text-[11px] font-black tracking-[0.3em] text-white/25 uppercase mb-8">
              Early Access
            </span>
          </FadeSection>

          <FadeSection delay={0.08}>
            <h2 className="text-5xl md:text-7xl font-black tracking-tight leading-tight mb-6">
              Join the Waitlist.
            </h2>
          </FadeSection>

          <FadeSection delay={0.14}>
            <p className="text-gray-500 text-lg mb-14 max-w-lg mx-auto leading-relaxed">
              Be the first to access the Map2Close AI Sales Assistant. Limited spots for early teams.
            </p>
          </FadeSection>

          <FadeSection delay={0.2}>
            <Link
              href="https://sales.map2close.com/meetings/kenzo/disco?uuid=f3fa6679-849d-4d9e-85de-c4525efb4f96"
              target="_blank"
              className="group inline-flex items-center gap-3 bg-[#62D2A2] text-black px-10 py-5 font-black text-sm uppercase tracking-widest rounded-full hover:bg-[#7ddbae] transition-all duration-300"
            >
              Request Early Access
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Link>
          </FadeSection>

          <FadeSection delay={0.28}>
            <p className="mt-10 text-gray-600 text-sm">
              Or{" "}
              <Link href="/services" className="text-gray-400 hover:text-white transition-colors underline underline-offset-4">
                explore all services
              </Link>
            </p>
          </FadeSection>
        </div>
      </section>

    </div>
  );
}
