'use client';

import { motion } from 'framer-motion';
import styles from './MetricsSection.module.css';

export default function MetricsSection() {
  const metrics = [
    {
      value: '3-5x',
      label: 'Meeting Lift',
      description: 'Increase in qualified discovery calls generated by reps.'
    },
    {
      value: '40%',
      label: 'Trial Engagement',
      description: 'Improvement in prospect interaction natively measured within active trials.'
    },
    {
      value: '10-25%',
      label: 'Higher Connect Rates',
      description: 'Nailing the message instantly results in dramatically better engagement.'
    }
  ];

  return (
    <section className={styles.metricsSection}>
      <div className={styles.container}>
        <div className={styles.grid}>
          {metrics.map((metric, index) => (
            <motion.div 
              key={index}
              className={styles.metricCard}
              initial={{ opacity: 0, scale: 0.8 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true, amount: 0.1 }}
              transition={{ duration: 0.6, delay: index * 0.2, ease: "easeOut" }}
            >
              <h3 className={styles.value}>{metric.value}</h3>
              <h4 className="sub-heading">{metric.label}</h4>
              <p className="body-text">{metric.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
